### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by Machou**

### CODE REVIEW

**Comment by funkydude** [comment]
What are you trying to accomplish here? This is not how you report an issue.

**Comment by funkydude** [comment]
No response... closing this. Please report issues by using the "issues" section. I have no idea what made you think you had to modify a file in the repository to report an issue.

**Comment by Machou** [comment]
I don't understand how to post new spam ...

**Comment by funkydude** [comment]
You click the issues tab, you select new issue, you read the description.
You follow the instructions, and you add that link to the issue you just created.

You created an issue with spam previously, you were half way there. You need to create an issue with a link to the spam.

There is no need to fork this addon to reports issues, you can safely delete your fork.

**Pull request closed without merging**
